### ISSUE TITLE
WordPress Powered by AMIMOTO (HVM) + WordPress 4.6でユーザー登録するとPHPエラーが出力される

### ISSUE THREAD

**Issue by mt8** [megumiteam/amimoto#12]
一部コアの問題のような気もしますが、ここでも報告させて頂きます。

### ユーザーをダッシュボードから新規追加

ユーザー名：test
メールアドレス：test@example.com

### エラーメッセージ

```
Fatal error: Uncaught exception 'phpmailerException' with message 'Invalid address: wordpress@_' in /var/www/vhosts/i-XXXXXXXX/wp-includes/class-phpmailer.php:946
Stack trace:
#0 /var/www/vhosts/i-XXXXXXXX/wp-includes/pluggable.php(352): PHPMailer->setFrom('wordpress@_', 'WordPress')
#1 /var/www/vhosts/i-XXXXXXXX/wp-includes/pluggable.php(1726): wp_mail('hogehoge@...', '[SITE NAME]')
#2 /var/www/vhosts/i-XXXXXXXX/wp-includes/user.php(2350): wp_new_user_notification(35, NULL, 'both')
#3 [internal function]: wp_send_new_user_notifications(35, 'both')
#4 /var/www/vhosts/i-XXXXXXXX/wp-includes/plugin.php(524): call_user_func_array('wp_send_new_use...', Array)
#5 /var/www/vhosts/i-XXXXXXXX/wp-admin/includes/user.php(196): do_action('edit_user_creat...', 35, 'both')
#6 /var/www/vhosts/i-XXXXXXXX/wp-admin/user-new.php(116): edit_user()
#7 {main} thrown in /var/www/vhosts/i-XXXXXXXX/wp-includes/class-phpmailer.php on line 946
```

### 原因

WordPress4.6より、```wp_mailメソッド```内で、phpMailerの```setFromメソッド```が使用されることになっている。
参考：https://core.trac.wordpress.org/changeset/38287

Nginx環境下だと、```$_SERVER['SERVER_NAME']```の値は```_```となっており、メールアドレスが```wordpress@_```となる。
以上により、phpMailerの```setFromメソッド```が例外を発生させる。

ちなみに、```$_SERVER['SERVER_NAME']```の値を参照するかはコアのチケットでもやりとりされているがマイルストーンはついていない。
参考：https://core.trac.wordpress.org/ticket/25239

### 対策

wp_mailのfromメールアドレスはフィルターで書き換え可能なので、今のところ以下で回避しています。

```
function my_wp_mail_from( $original_email_address ) {
	return 'wordpress@' . parse_url( get_home_url( get_current_blog_id() ), PHP_URL_HOST );
}
add_filter( 'wp_mail_from', 'my_wp_mail_from' );
```

**Comment by hideokamoto** [comment]
https://github.com/amimoto-ami/amimoto-dashboard/releases/tag/v_0.3.0
AMIMOTO Dashboardプラグインにてパッチファイルをつけるようにしました。
